In [1]:
x = 1

In [7]:
temperaturas = [4, 7, 9]
promedio = sum(temperaturas) / len(temperaturas)
promedio
temperaturas

[4, 7, 9]

In [15]:
consumos = 10

In [16]:
print(consumos)

10

In [17]:
import pandas as pd

In [29]:
simpsons = pd.read_csv("SimpsonsData.csv")

In [21]:
simpsons

,Season,Title,Airdate,Rating,Vote_count,Description
0,1,Simpsons Roasting on an Open Fire,17 Dec. 1989,8.2,5633.0,The family is forced to spend all of their sav...
1,1,Bart the Genius,14 Jan. 1990,7.7,3580.0,Bart ends up at a school for gifted children a...
2,1,Homer's Odyssey,21 Jan. 1990,7.4,3145.0,"After losing his job, Homer contemplates endin..."
3,1,There's No Disgrace Like Home,28 Jan. 1990,7.7,3087.0,After being embarrassed by the rest of the fam...
4,1,Bart the General,4 Feb. 1990,8.0,3130.0,After being beaten up by Nelson Muntz one too ...
...,...,...,...,...,...,...
679,31,Warrin' Priests,26 Apr. 2020,6.0,332.0,Reverend Lovejoy investigates the mysterious p...
680,31,Warrin' Priests Part 2,3 May 2020,5.7,296.0,"In Michigan, Reverend Lovejoy learns the true ..."
681,31,The Hateful Eight-Year-Olds,10 May 2020,6.7,277.0,Lisa joins a group of rich girls when she make...
682,31,The Way of the Dog,17 May 2020,7.4,288.0,The Simpsons explore the tragic past of Santa'...
683,32,Episode #32.1,27 Sep. 2020,NaN,NaN,Know what this is about? Be the first one to a...

In [22]:
type(simpsons)

pandas.DataFrame

In [25]:
simpsons.head(3)

,Season,Title,Airdate,Rating,Vote_count,Description
0,1,Simpsons Roasting on an Open Fire,17 Dec. 1989,8.2,5633.0,The family is forced to spend all of their sav...
1,1,Bart the Genius,14 Jan. 1990,7.7,3580.0,Bart ends up at a school for gifted children a...
2,1,Homer's Odyssey,21 Jan. 1990,7.4,3145.0,"After losing his job, Homer contemplates endin..."

In [26]:
simpsons.tail(3)

,Season,Title,Airdate,Rating,Vote_count,Description
681,31,The Hateful Eight-Year-Olds,10 May 2020,6.7,277.0,Lisa joins a group of rich girls when she make...
682,31,The Way of the Dog,17 May 2020,7.4,288.0,The Simpsons explore the tragic past of Santa'...
683,32,Episode #32.1,27 Sep. 2020,NaN,NaN,Know what this is about? Be the first one to a...

In [32]:
simpsons.shape

(684, 6)

In [33]:
simpsons.columns

Index(['Season', 'Title', 'Airdate', 'Rating', 'Vote_count', 'Description'], dtype='str')

In [34]:
simpsons.dtypes

Season           int64
Title              str
Airdate            str
Rating         float64
Vote_count     float64
Description        str
dtype: object

In [35]:
simpsons.info()

<class 'pandas.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Season       684 non-null    int64
 1   Title        684 non-null    str
 2   Airdate      684 non-null    str
 3   Rating       683 non-null    float64
 4   Vote_count   683 non-null    float64
 5   Description  684 non-null    str
dtypes: float64(2), int64(1), str(3)
memory usage: 32.2 KB

In [37]:
calificaciones = simpsons["Rating"]
calificaciones

0      8.2
1      7.7
2      7.4
3      7.7
4      8.0
      ...
679    6.0
680    5.7
681    6.7
682    7.4
683    NaN
Name: Rating, Length: 684, dtype: float64

In [42]:
list(simpsons["Title"])[0]

'Simpsons Roasting on an Open Fire'

In [40]:
simpsons[["Title", "Season", "Rating"]]

                                 Title  Season  Rating
0    Simpsons Roasting on an Open Fire       1     8.2
1                      Bart the Genius       1     7.7
2                      Homer's Odyssey       1     7.4
3        There's No Disgrace Like Home       1     7.7
4                     Bart the General       1     8.0
..                                 ...     ...     ...
679                    Warrin' Priests      31     6.0
680             Warrin' Priests Part 2      31     5.7
681        The Hateful Eight-Year-Olds      31     6.7
682                 The Way of the Dog      31     7.4
683                      Episode #32.1      32     NaN

[684 rows x 3 columns]

In [43]:
simpsons["Rating"] > 7.5

0       True
1       True
2      False
3       True
4       True
       ...
679    False
680    False
681    False
682    False
683    False
Name: Rating, Length: 684, dtype: bool

In [46]:
s2 = simpsons[simpsons["Rating"] > 7.5]

In [47]:
type(s2)

pandas.DataFrame